"""Константы конфигурации проекта."""

# Максимальные длины полей моделей пользователей
USER_EMAIL_MAX_LENGTH = 254
USER_PHONE_MAX_LENGTH = 32
USER_CHOICE_MAX_LENGTH = 20
USER_TELEGRAM_USERNAME_MAX_LENGTH = 100
USER_SESSION_TOKEN_MAX_LENGTH = 255

# Максимальные длины полей анкет
SURVEY_TITLE_MAX_LENGTH = 200
STEP_TITLE_MAX_LENGTH = 200
QUESTION_LABEL_MAX_LENGTH = 300
OPTION_VALUE_MAX_LENGTH = 100
OPTION_LABEL_MAX_LENGTH = 200
DOCUMENT_LABEL_MAX_LENGTH = 200
STATUS_MAX_LENGTH = 20
STEP_CODE_MAX_LENGTH = 64
QUESTION_TYPE_MAX_LENGTH = 20
SURVEY_CODE_MAX_LENGTH = 64
QUESTION_CODE_MAX_LENGTH = 64
OPTION_ORDER_DEFAULT = 0
