line-length = 88
target-version = "py311"
extend-exclude = [
    "backend/config/settings.py",
    "*/migrations/*",
    "venv",
    ".venv",
    "frontend/node_modules",
    "node_modules",
    "build",
    "dist",
]

[lint]
select = ["E", "F", "I", "W"]
ignore = ["E501"]

[format]
docstring-code-format = true
