# Generated by Django 5.2.6 on 2025-09-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход в систему'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_platform_used',
            field=models.CharField(blank=True, choices=[('web', 'Веб-интерфейс'), ('telegram', 'Телеграм')], max_length=20, null=True, verbose_name='Последняя используемая платформа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_telegram_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность в Telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_website_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность на сайте'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_platform',
            field=models.CharField(blank=True, choices=[('web', 'Веб-интерфейс'), ('telegram', 'Телеграм')], max_length=20, null=True, verbose_name='Основная платформа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('analyst', 'Аналитик'), ('viewer', 'Наблюдатель')], default='viewer', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Идентификатор чата в Telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя в Telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website_session_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Токен сессии на сайте'),
        ),
    ]
