# Generated by Django 5.2.6 on 2025-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('applicant', 'Заявитель'), ('employee', 'Сотрудник'), ('admin', 'Администратор')], default='applicant', max_length=20, verbose_name='Роль'),
        ),
    ]
