# Generated by Django 5.2.6 on 2025-09-28 15:04

import uuid

from django.db import migrations
from django.db.models import Count, Q


def fill_missing_phones(apps, schema_editor):
    User = apps.get_model('users', 'User')

    duplicates = (
        User.objects.exclude(phone__isnull=True)
        .exclude(phone='')
        .values('phone')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )
    if duplicates.exists():
        duplicated_values = ', '.join(sorted(item['phone'] for item in duplicates))
        raise ValueError(
            'Найдено несколько пользователей с одинаковыми телефонами: '
            f'{duplicated_values}. Исправьте данные до запуска миграций.'
        )

    queryset = User.objects.filter(Q(phone__isnull=True) | Q(phone=''))
    for user in queryset.iterator():
        user.phone = uuid.uuid4().hex[:32]
        user.save(update_fields=['phone'])


def noop_reverse(*args, **kwargs):
    raise migrations.IrreversibleError('Заполнение номеров телефонов нельзя отменить автоматически.')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(fill_missing_phones, noop_reverse),
    ]
