# Generated by Django 5.2.6 on 2025-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fill_phone_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                max_length=32,
                unique=True,
                verbose_name='Номер телефона',
            ),
        ),
    ]
