# Generated by Django 5.2.6 on 2025-09-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_schema_sync"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Текст"),
                    ("textarea", "Многострочный текст"),
                    ("email", "Email"),
                    ("phone", "Телефон"),
                    ("date", "Дата"),
                    ("boolean", "Булево"),
                    ("select", "Выбор из списка"),
                    ("multiselect", "Несколько из списка"),
                    ("file", "Файл"),
                    ("file_multi", "Несколько файлов"),
                    ("number", "Число"),
                    ("select_one", "Один из списка (legacy)"),
                    ("select_many", "Несколько из списка (legacy)"),
                    ("yes_no", "Да/Нет (legacy)"),
                ],
                max_length=20,
                verbose_name="Тип вопроса",
            ),
        ),
    ]
