# Generated by Django 5.2.6 on 2025-09-30 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0003_alter_question_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        blank=True,
                        help_text="Служебный код (обычно совпадает с требованием).",
                        max_length=64,
                        verbose_name="Код документа",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Отображаемое имя документа.",
                        max_length=200,
                        verbose_name="Название",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Архивирован"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="applications.application",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="applications.documentrequirement",
                        verbose_name="Требование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор версии",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Номер версии"),
                ),
                (
                    "file_key",
                    models.CharField(max_length=512, verbose_name="Ключ в хранилище"),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Исходное имя файла"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME-тип"),
                ),
                ("size", models.BigIntegerField(verbose_name="Размер файла")),
                (
                    "checksum",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Контрольная сумма"
                    ),
                ),
                (
                    "etag",
                    models.CharField(blank=True, max_length=128, verbose_name="ETag"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает загрузки"),
                            ("uploaded", "Загружен"),
                            ("available", "Готов к использованию"),
                            ("rejected", "Отклонён"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "antivirus_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает проверки"),
                            ("clean", "Проверен"),
                            ("infected", "Выявлено заражение"),
                            ("failed", "Ошибка проверки"),
                            ("skipped", "Проверка не выполнялась"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус антивирусной проверки",
                    ),
                ),
                (
                    "antivirus_message",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий проверки"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время загрузки"
                    ),
                ),
                (
                    "ready_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Готово к использованию"
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Доп. сведения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загружен пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия документа",
                "verbose_name_plural": "Версии документов",
                "ordering": ("-created_at", "-id"),
                "unique_together": {("document", "version")},
            },
        ),
        migrations.CreateModel(
            name="DocumentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Создан"),
                            ("upload_requested", "Запрошена загрузка"),
                            ("upload_completed", "Загрузка завершена"),
                            ("status_changed", "Изменение статуса"),
                            ("archived", "Документ архивирован"),
                        ],
                        max_length=32,
                        verbose_name="Тип события",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Данные"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="documents.document",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="documents.documentversion",
                        verbose_name="Версия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие документа",
                "verbose_name_plural": "События документа",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_documents",
                to="documents.documentversion",
                verbose_name="Текущая версия",
            ),
        ),
    ]
