name: Deploy Production

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH sanity check (whoami@host)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            echo "Connected as: $(whoami)"
            hostname

      - name: Sync project to remote host
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -az --delete --exclude ".git/" --exclude "venv/" --exclude ".env" --exclude "backend/staticfiles/" --exclude "backend/media/"
          path: ./
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: user8
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}

      - name: Apply docker compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd "${{ secrets.REMOTE_PATH }}"
            docker compose -f docker/docker-compose.prod.yml down
            docker compose -f docker/docker-compose.prod.yml up -d --build --remove-orphans
            docker compose -f docker/docker-compose.prod.yml exec -T backend python backend/manage.py migrate --noinput
            docker compose -f docker/docker-compose.prod.yml exec -T backend python backend/manage.py collectstatic --noinput